
import { Unit } from './types';

export const UNITS: Unit[] = [
  {
    id: 1,
    title: "單元一：數詞",
    icon: "🔢",
    color: "bg-blue-400",
    words: [
      { id: "1-1", text: "一", emoji: "1️⃣" },
      { id: "1-2", text: "二", emoji: "2️⃣" },
      { id: "1-3", text: "三", emoji: "3️⃣" },
      { id: "1-4", text: "四", emoji: "4️⃣" },
      { id: "1-5", text: "五", emoji: "5️⃣" },
      { id: "1-6", text: "六", emoji: "6️⃣" },
      { id: "1-7", text: "七", emoji: "7️⃣" },
      { id: "1-8", text: "八", emoji: "8️⃣" },
      { id: "1-9", text: "九", emoji: "9️⃣" },
      { id: "1-10", text: "十", emoji: "🔟" },
      { id: "1-11", text: "兩", emoji: "✌️" },
      { id: "1-12", text: "百", emoji: "💯" },
      { id: "1-13", text: "萬", emoji: "♾️" },
    ]
  },
  {
    id: 2,
    title: "單元二：顏色",
    icon: "🎨",
    color: "bg-pink-400",
    words: [
      { id: "2-1", text: "綠色", emoji: "🟢" },
      { id: "2-2", text: "黃色", emoji: "🟡" },
      { id: "2-3", text: "白色", emoji: "⚪" },
      { id: "2-4", text: "黑色", emoji: "⚫" },
      { id: "2-5", text: "藍色", emoji: "🔵" },
      { id: "2-6", text: "灰色", emoji: "🔘" },
      { id: "2-7", text: "紅色", emoji: "🔴" },
    ]
  },
  {
    id: 3,
    title: "單元三：身體",
    icon: "🧒",
    color: "bg-yellow-400",
    words: [
      { id: "3-1", text: "心", emoji: "❤️" },
      { id: "3-2", text: "頭", emoji: "🙆‍♂️" },
      { id: "3-3", text: "眼睛", emoji: "👁️" },
      { id: "3-4", text: "耳朵", emoji: "👂" },
      { id: "3-5", text: "臉", emoji: "👤" },
      { id: "3-6", text: "鼻子", emoji: "👃" },
      { id: "3-7", text: "嘴巴", emoji: "👄" },
      { id: "3-8", text: "頭髮", emoji: "💇‍♀️" },
      { id: "3-9", text: "腳", emoji: "🦶" },
      { id: "3-10", text: "身體", emoji: "🧍" },
      { id: "3-11", text: "背", emoji: "🔙" },
      { id: "3-12", text: "樣子", emoji: "🧒" },
    ]
  },
  {
    id: 4,
    title: "單元四：家庭/人物",
    icon: "👨‍👩‍👧‍👦",
    color: "bg-green-400",
    words: [
      { id: "4-1", text: "家人", emoji: "👨‍👩‍👧‍👦" },
      { id: "4-2", text: "媽媽", emoji: "👩" },
      { id: "4-3", text: "母親", emoji: "👩‍🍼" },
      { id: "4-4", text: "弟弟", emoji: "👦" },
      { id: "4-5", text: "哥哥", emoji: "👨‍🎓" },
      { id: "4-6", text: "老師", emoji: "👩‍🏫" },
      { id: "4-7", text: "父親", emoji: "👨" },
      { id: "4-8", text: "爺爺", emoji: "👴" },
      { id: "4-9", text: "同學", emoji: "🧑‍🤝‍🧑" },
      { id: "4-10", text: "妹妹", emoji: "👧" },
      { id: "4-11", text: "爸爸", emoji: "🧔" },
      { id: "4-12", text: "叔叔", emoji: "🤵" },
      { id: "4-13", text: "舅舅", emoji: "👱‍♂️" },
      { id: "4-14", text: "小朋友", emoji: "🧒" },
    ]
  },
  {
    id: 5,
    title: "單元五：物品",
    icon: "🧸",
    color: "bg-purple-400",
    words: [
      { id: "5-1", text: "書", emoji: "📖" },
      { id: "5-2", text: "圍裙", emoji: "🎽" },
      { id: "5-3", text: "東西", emoji: "📦" },
      { id: "5-4", text: "風箏", emoji: "🪁" },
      { id: "5-5", text: "桌子", emoji: "🪑" },
      { id: "5-6", text: "書包", emoji: "🎒" },
      { id: "5-7", text: "帽子", emoji: "👒" },
      { id: "5-8", text: "鉛筆", emoji: "✏️" },
      { id: "5-9", text: "玩具", emoji: "🧸" },
      { id: "5-10", text: "衣服", emoji: "👕" },
      { id: "5-11", text: "床", emoji: "🛌" },
      { id: "5-12", text: "禮物", emoji: "🎁" },
      { id: "5-13", text: "鏡子", emoji: "🪞" },
      { id: "5-14", text: "鞋子", emoji: "👟" },
      { id: "5-15", text: "氣球", emoji: "🎈" },
    ]
  },
  {
    id: 6,
    title: "單元六：其他",
    icon: "🌟",
    color: "bg-orange-400",
    words: [
      { id: "6-1", text: "聲音", emoji: "🔊" },
      { id: "6-2", text: "地方", emoji: "📍" },
      { id: "6-3", text: "學校", emoji: "🏫" },
      { id: "6-4", text: "中國", emoji: "🇨🇳" },
      { id: "6-5", text: "國家", emoji: "🏳️" },
      { id: "6-6", text: "故事", emoji: "📔" },
      { id: "6-7", text: "工作", emoji: "💼" },
      { id: "6-8", text: "生活", emoji: "🏠" },
      { id: "6-9", text: "事情", emoji: "📋" },
      { id: "6-10", text: "早上", emoji: "🌅" },
      { id: "6-11", text: "時間", emoji: "⏰" },
      { id: "6-12", text: "星期", emoji: "📅" },
      { id: "6-13", text: "生日", emoji: "🎂" },
      { id: "6-14", text: "新年", emoji: "🧧" },
      { id: "6-15", text: "遊戲", emoji: "🎮" },
    ]
  },
  {
    id: 7,
    title: "單元七：自然",
    icon: "🌳",
    color: "bg-teal-400",
    words: [
      { id: "7-1", text: "春天", emoji: "🌸" },
      { id: "7-2", text: "天空", emoji: "☁️" },
      { id: "7-3", text: "世界", emoji: "🌍" },
      { id: "7-4", text: "月亮", emoji: "🌙" },
      { id: "7-5", text: "太陽", emoji: "☀️" },
      { id: "7-6", text: "天氣", emoji: "🌦️" },
      { id: "7-7", text: "夏天", emoji: "🏖️" },
      { id: "7-8", text: "秋天", emoji: "🍂" },
      { id: "7-9", text: "冬天", emoji: "❄️" },
      { id: "7-10", text: "陽光", emoji: "🌞" },
      { id: "7-11", text: "空氣", emoji: "💨" },
      { id: "7-12", text: "森林", emoji: "🌲" },
      { id: "7-13", text: "草地", emoji: "🌱" },
      { id: "7-14", text: "泥土", emoji: "🪵" },
      { id: "7-15", text: "石頭", emoji: "🪨" },
    ]
  },
  {
    id: 8,
    title: "單元八：食物",
    icon: "🍎",
    color: "bg-red-400",
    words: [
      { id: "8-1", text: "水果", emoji: "🍎" },
      { id: "8-2", text: "西瓜", emoji: "🍉" },
      { id: "8-3", text: "香蕉", emoji: "🍌" },
      { id: "8-4", text: "葡萄", emoji: "🍇" },
      { id: "8-5", text: "蘋果", emoji: "🍏" },
      { id: "8-6", text: "蘿蔔", emoji: "🥕" },
      { id: "8-7", text: "白菜", emoji: "🥬" },
      { id: "8-8", text: "蛋", emoji: "🥚" },
      { id: "8-9", text: "米", emoji: "🍚" },
      { id: "8-10", text: "麵包", emoji: "🍞" },
      { id: "8-11", text: "巧克力", emoji: "🍫" },
      { id: "8-12", text: "蛋糕", emoji: "🎂" },
    ]
  }
];
